language: python
python:
  - "2.7"
services:
  - postgresql
before_script:
  - cd project; python manage.py migrate
script:
  - cd project; python manage.py test
install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
