version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - run:
          name: Instalando dependencias
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Ejecutando test
          command: pipenv run "python manage.py test"


---

test:
  override:
    - coverage run manage.py test
deployment:
  production:
    branch: master
    commands:
      - git remote add dokku dokku@enjambrelab.com.ar:suite-backend
      - git push dokku master:master
  production_dtelab:
    branch: produccion
    commands:
      - git remote add dokku2 dokku@dtelab.com.ar:suite2-backend
      - git push dokku2 produccion:master
